spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ssh://localhost/config-repo2
        clone-on-start: true

server:
  port: 8888

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
